<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ConsoleCafe.Domain\ConsoleCafe.Domain.csproj" />
		<ProjectReference Include="..\ConsoleCafe.Application\ConsoleCafe.Application.csproj" />
		<ProjectReference Include="..\ConsoleCafe.Infrastructure\ConsoleCafe.Infrastructure.csproj" />
	</ItemGroup>
	
</Project>
